Repository AY2223S2-CS2103T-T17-4/tp, pull requests merged in 2023-03, with the labels that each got.

#28 Change CI link
  README.md
Labels: priority.Low, severity.Low

#30 Fix inability to save tasks
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/task/TaskAddCommand.java
  src/main/java/seedu/address/model/TaskList.java
Labels: type.Bug

#36 Add Tank model package files
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTankList.java
  src/main/java/seedu/address/model/ReadOnlyTaskList.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/TankList.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/tank/Tank.java
  src/main/java/seedu/address/model/tank/TankName.java
  src/main/java/seedu/address/model/tank/UniqueTankList.java
  src/main/java/seedu/address/model/tank/exceptions/DuplicateTankException.java
  src/main/java/seedu/address/model/tank/exceptions/TankNotFoundException.java
  src/main/java/seedu/address/model/util/SampleTankUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High

#63 Fix fish delete not updating a Tank's fish list
  src/main/java/seedu/address/logic/commands/fish/FishDeleteCommand.java
Labels: type.Bug, severity.Medium

#80 Improve User Guide
  docs/UserGuide.md
Labels: priority.High

#87 Update DG and UG
  docs/2103UG.pptx
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FeedingReminderSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FeedingReminderSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/logo_DG.png
  docs/images/logo_UG.png
Labels: type.Task, type.Bug

#94 Add Table of Contents
  docs/DeveloperGuide.md
Labels: priority.High

#108 Change Priority to use Enums
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
Labels: priority.High

#110 Fix exception when tank is deleted when fish and tasks present
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/tank/TankDeleteCommand.java
  src/test/java/seedu/address/logic/commands/tank/TankDeleteCommandTest.java
Labels: priority.High, severity.VeryHigh

#111 Minor text changes
  src/main/java/seedu/address/logic/commands/fish/FishSortCommand.java
  src/main/java/seedu/address/model/fish/Fish.java
Labels: priority.Low, severity.Low

#119 Add Task sorting functionality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/tank/TankViewCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Priority.java
Labels: priority.High, severity.Medium

#120 Add a Help window
  build.gradle
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.Medium

#128 Implement task edit
  src/main/java/seedu/address/logic/commands/task/TaskCommand.java
  src/main/java/seedu/address/logic/commands/task/TaskEditCommand.java
  src/main/java/seedu/address/logic/parser/task/TaskEditCommandParser.java
  src/main/java/seedu/address/logic/parser/task/TaskParser.java
  src/main/java/seedu/address/model/task/Task.java
Labels: type.Task, priority.Medium

#117 Implement command to delete latest readings given tank index
  src/main/java/seedu/address/logic/commands/tank/TankCommand.java
  src/main/java/seedu/address/logic/commands/tank/TankDeleteCommand.java
  src/main/java/seedu/address/logic/commands/tank/readings/ReadingsDeleteLastCommand.java
  src/main/java/seedu/address/logic/parser/tank/TankParser.java
  src/main/java/seedu/address/logic/parser/tank/readings/ReadingAddCommandParser.java
  src/main/java/seedu/address/logic/parser/tank/readings/ReadingDeleteLastCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tank/readings/Reading.java
  src/main/java/seedu/address/model/tank/readings/UniqueIndividualReadingLevels.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/tank/TankAddCommandTest.java
Labels: type.Story, type.Task, priority.High

#132 Change App Icon
  docs/2103UG.pptx
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/FishAhoyIcon.png
Labels: priority.High

#129 Delete feeding reminder for tank in tank feed
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/tank/TankFeedCommand.java
Labels: type.Enhancement, priority.Medium

#135 Update user guide and offline help window html
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/resources/html/UserManual.html
  src/main/resources/html/images/helpMessage.png
Labels: type.Task, priority.Medium

#140 Added new Ui pictures and add Ui introduction
  docs/2103UG.pptx
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiIntro.png
  docs/images/UiOld.png
Labels: type.Enhancement, priority.High

#141 Fix minor bugs
  docs/UserGuide.md
Labels: type.Bug, priority.High
