Repository AY2223S2-CS2103T-T17-4/tp, pull requests merged in 2023-04, with the labels that each got.

#203 PED fixes
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/fish/FishAddCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High

#218 Fix #217, fix feeding interval comparator
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/fish/FishSortCommandParser.java
  src/main/java/seedu/address/model/fish/FeedingInterval.java
Labels: priority.Medium, severity.Medium

#216 Update Acknowledgements
  docs/DeveloperGuide.md
  docs/diagrams/FishSortDiagram.puml
  docs/images/FishSortDiagram.png
  src/main/java/seedu/address/logic/commands/fish/FishSortCommand.java
Labels: priority.High

#219 Update user guide
  docs/UserGuide.md
Labels: type.Task, type.Bug, priority.High

#221 Fix task edit bug
  src/main/java/seedu/address/logic/commands/task/TaskEditCommand.java
  src/main/java/seedu/address/logic/parser/task/TaskEditCommandParser.java
Labels: type.Bug, severity.Medium

#224 Remove equipment package and improve readings error message
  src/main/java/seedu/address/model/tank/equipment/Equipment.java
  src/main/java/seedu/address/model/tank/equipment/EquipmentName.java
  src/main/java/seedu/address/model/tank/equipment/EquipmentStatus.java
  src/main/java/seedu/address/model/tank/equipment/EquipmentType.java
  src/main/java/seedu/address/model/tank/equipment/LastMaintainedDate.java
  src/main/java/seedu/address/model/tank/readings/AmmoniaLevel.java
  src/main/java/seedu/address/model/tank/readings/PH.java
  src/main/java/seedu/address/model/tank/readings/Temperature.java
Labels: type.Bug, severity.Low

#222 Fix listing all fishes after add or edit fish
  src/main/java/seedu/address/logic/commands/fish/FishEditCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, severity.Medium

#226 Fix data files other than addressbook corruption not working
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/tank/readings/ammonialevels/JsonAdaptedIndividualReadingLevels.java
Labels: type.Bug, severity.Medium

#231 Add Ui explanations on Fish and Tank
  docs/2103UG.pptx
  docs/UserGuide.md
  docs/images/UiFish.png
  docs/images/UiTank.png
Labels: type.Enhancement

#234 Remove list tanks command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, type.Bug, priority.Medium, severity.Medium

#233 Fix task no duplicate check and update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/task/TaskAddCommand.java
  src/main/java/seedu/address/model/task/Task.java
Labels: type.Bug, priority.Medium, severity.Medium

#243 Increase test coverage
  src/main/java/seedu/address/logic/commands/tank/readings/ReadingsAddCommand.java
  src/test/java/seedu/address/logic/commands/tank/readings/ReadingsAddCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TaskAddCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TaskDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/task/TaskEditCommandTest.java
Labels: type.Task

#246 Change LFD display value
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/date/DateUtil.java
  src/main/java/seedu/address/model/fish/LastFedDateTime.java
Labels: type.Bug, severity.Medium
